# DENSO888 Professional Configuration
app:
  name: 'DENSO888 Professional'
  version: '3.0.0'
  company: 'DENSO Thailand'

database:
  default_type: 'sqlserver'
  pool:
    min_size: 5
    max_size: 20
    timeout: 30
    pre_ping: true

excel:
  chunk_size: 5000
  max_file_size: 100MB
  supported_formats:
    - xlsx
    - xls
    - xlsm

backup:
  enabled: true
  interval: 30
  retention_days: 7
  compress: true

logging:
  level: INFO
  rotation: 10MB
  backups: 5

ui:
  theme: 'modern'
  language: 'en'
  animations: true
