# Database Configuration
databases:
  sqlite:
    file: "denso888_data.db"
    timeout: 30
  
  sqlserver:
    host: "localhost"
    database: "denso888"
    port: 1433
    driver: "ODBC Driver 17 for SQL Server"
    pool_size: 5
    max_overflow: 10
    
connections:
  default: "sqlite"
  production: "sqlserver"
